#!/bin/bash

# generates a README.md for a directory of Xcode Snippets
# requires XMLStarlet

cat <<static
# xcode-snippets

My Xcode Snippets

## Installation

Copy files to \`~/Library/Developer/Xcode/UserData/CodeSnippets\`

## Cheat Sheet

Command  | Description
------------- | -------------
static

suffix="codesnippet"
for snippet in `ls *.$suffix`;
do
    echo $(xml sel --net -t \
                         -o \` \
                         -v "/plist/dict[1]/key[.='IDECodeSnippetCompletionPrefix']/following-sibling::string[1]" \
                         -o \`\| \
                         -v "/plist/dict[1]/key[.='IDECodeSnippetSummary']/following-sibling::string[1]" \
                                $snippet)
done;

cat <<about

## About this file

This README was generated by \`${0##*/}\`. Each snippet was named using \`rename.sh\`.

Perform these tasks automatically by including the execution of these scripts 
in a git pre-commit hook.

Example:

    ./rename.sh
    ./generate_readme.sh > README.md

    # include the generated files
    git add -A

about
